version: '3.8'

services:
  # üåê API principal - PROD
  anprvision-api-prod:
    container_name: anprvision-api-prod
    build:
      context: ../..             # ra√≠z del proyecto
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5103:8080"
    networks:
      - anprvision_network
    labels:
      - com.anprvision.environment=prod

networks:
  anprvision_network:
    external: true
