services:
  anprvision-api-develop:
    container_name: anprvision-api-develop
    image: anprvision-api-develop:latest
    build:
      context: ../..
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5100:8080"
    networks:
      - anpr-net-develop
    labels:
      - com.anprvision.environment=develop

networks:
  anpr-net-develop:
    external: true

