version: '3.8'

services:
  # üåê API principal - DEVELOP
  anprvision-api-develop:
    container_name: anprvision-api-develop
    build:
      context: ../..         # ra√≠z del proyecto
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5100:8080"
    networks:
      - anprvision_network
    labels:
      - com.anprvision.environment=develop

networks:
  anprvision_network:
    external: true
