services:
  anprvision-api-develop:
    container_name: anprvision-api-develop
    image: anprvision-api-develop:latest
    build:
      context: ../..
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5100:8080"
    networks:
      - anpr-net-develop
    depends_on:
      - postgres_external
    labels:
      - com.anprvision.environment=develop

  postgres_external:
    external: true
    name: anprvision-postgres-develop

networks:
  anpr-net-develop:
    external: true

