version: '3.9'

services:
  # üåê Backend principal ANPR Vision - DEVELOP
  anprvision-api-develop:
    container_name: anprvision-api-develop
    image: anprvision-api-develop:latest
    build:
      context: ../..
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5100:8080"        # ‚Üê Puerto √∫nico para develop
    networks:
      - anpr-net-develop
    depends_on:
      - anprvision-postgres-develop
    labels:
      - com.anprvision.environment=develop

networks:
  anpr-net-develop:
    external: true

