version: '3.9'

services:
  # ğŸŒ Backend principal ANPR Vision - STAGING
  anprvision-api-staging:
    container_name: anprvision-api-staging
    image: anprvision-api-staging:latest
    build:
      context: ../..
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5300:8080"        # â† Puerto Ãºnico para Staging
    networks:
      - anpr-net-staging
    depends_on:
      - anprvision-postgres-staging
    labels:
      - com.anprvision.environment=staging

networks:
  anpr-net-staging:
    external: true

