version: '3.8'

services:
  # üåê API principal - STAGING
  anprvision-api-staging:
    container_name: anprvision-api-staging
    build:
      context: ../..            # ra√≠z del proyecto
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5102:8080"
    networks:
      - anprvision_network
    labels:
      - com.anprvision.environment=staging

networks:
  anprvision_network:
    external: true
