version: '3.8'

services:
  # üåê API principal - QA
  anprvision-api-qa:
    container_name: anprvision-api-qa
    build:
      context: ../..           # ra√≠z del proyecto
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5101:8080"
    networks:
      - anprvision_network
    labels:
      - com.anprvision.environment=qa

networks:
  anprvision_network:
    external: true