version: '3.9'

services:
  # üåê Backend principal ANPR Vision - QA
  anprvision-api-qa:
    container_name: anprvision-api-qa
    image: anprvision-api-qa:latest
    build:
      context: ../..
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5200:8080"        # ‚Üê Puerto √∫nico para QA
    networks:
      - anpr-net-qa
    labels:
      - com.anprvision.environment=qa

networks:
  anpr-net-qa:
    external: true

